{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1",
    "cveMetadata": {
        "cveId": "CVE-2024-23458",
        "assignerOrgId": "73c6f63b-efac-410d-a0a9-569700f85a04",
        "state": "PUBLISHED",
        "assignerShortName": "Zscaler",
        "dateReserved": "2024-01-17T15:15:47.221Z",
        "datePublished": "2024-08-06T15:22:58.963Z",
        "dateUpdated": "2024-08-06T15:22:58.963Z"
    },
    "containers": {
        "cna": {
            "affected": [
                {
                    "defaultStatus": "unaffected",
                    "platforms": [
                        "Windows"
                    ],
                    "product": "Client Connector",
                    "vendor": "Zscaler",
                    "versions": [
                        {
                            "lessThan": "4.2.0.190",
                            "status": "affected",
                            "version": "0",
                            "versionType": "custom"
                        }
                    ]
                }
            ],
            "credits": [
                {
                    "lang": "en",
                    "type": "finder",
                    "value": "Equinor Red Team"
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "supportingMedia": [
                        {
                            "base64": false,
                            "type": "text/html",
                            "value": "While copying individual autoupdater log files, reparse point check was missing which could result into crafted attacks, potentially leading to a local privilege escalation. This issue affects Zscaler Client Connector on Windows &lt;4.2.0.190.<br>"
                        }
                    ],
                    "value": "While copying individual autoupdater log files, reparse point check was missing which could result into crafted attacks, potentially leading to a local privilege escalation. This issue affects Zscaler Client Connector on Windows <4.2.0.190."
                }
            ],
            "impacts": [
                {
                    "capecId": "CAPEC-233",
                    "descriptions": [
                        {
                            "lang": "en",
                            "value": "CAPEC-233 Privilege Escalation"
                        }
                    ]
                }
            ],
            "metrics": [
                {
                    "cvssV3_1": {
                        "attackComplexity": "LOW",
                        "attackVector": "LOCAL",
                        "availabilityImpact": "LOW",
                        "baseScore": 7.3,
                        "baseSeverity": "HIGH",
                        "confidentialityImpact": "HIGH",
                        "integrityImpact": "HIGH",
                        "privilegesRequired": "LOW",
                        "scope": "UNCHANGED",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:L",
                        "version": "3.1"
                    },
                    "format": "CVSS",
                    "scenarios": [
                        {
                            "lang": "en",
                            "value": "GENERAL"
                        }
                    ]
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-346",
                            "description": "CWE-346 Origin Validation Error",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "orgId": "73c6f63b-efac-410d-a0a9-569700f85a04",
                "shortName": "Zscaler",
                "dateUpdated": "2024-08-06T15:22:58.963Z"
            },
            "references": [
                {
                    "url": "https://help.zscaler.com/client-connector/client-connector-app-release-summary-2023?applicable_category=windows&applicable_version=4.2.0.190"
                }
            ],
            "source": {
                "discovery": "UNKNOWN"
            },
            "title": "Local Privilege Escalation on Zscaler Client Connector on Windows",
            "x_generator": {
                "engine": "Vulnogram 0.2.0"
            }
        }
    }
}