{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1",
    "cveMetadata": {
        "cveId": "CVE-2024-10344",
        "assignerOrgId": "ca2a266c-be2f-4d4b-92d0-47b76b1a9c4e",
        "state": "PUBLISHED",
        "assignerShortName": "Perforce",
        "dateReserved": "2024-10-24T13:48:10.942Z",
        "datePublished": "2024-11-11T14:08:11.753Z",
        "dateUpdated": "2024-11-11T14:08:11.753Z"
    },
    "containers": {
        "cna": {
            "affected": [
                {
                    "defaultStatus": "unaffected",
                    "product": "Helix Core",
                    "vendor": "Helix",
                    "versions": [
                        {
                            "lessThan": "2024.2",
                            "status": "affected",
                            "version": "0.0.0",
                            "versionType": "sem"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "supportingMedia": [
                        {
                            "base64": false,
                            "type": "text/html",
                            "value": "<span style=\"background-color: rgb(255, 255, 255);\">In Helix Core versions prior to 2024.2, an unauthenticated remote Denial of Service (DoS) via the refuse function was identified</span><span style=\"background-color: rgb(255, 255, 255);\">.  </span><span style=\"background-color: rgb(255, 255, 255);\">Reported by Karol </span><span style=\"background-color: rgb(255, 255, 255);\">Więsek</span><span style=\"background-color: rgb(255, 255, 255);\">.</span><br>"
                        }
                    ],
                    "value": "In Helix Core versions prior to 2024.2, an unauthenticated remote Denial of Service (DoS) via the refuse function was identified.  Reported by Karol Więsek."
                }
            ],
            "metrics": [
                {
                    "cvssV4_0": {
                        "Automatable": "NOT_DEFINED",
                        "Recovery": "NOT_DEFINED",
                        "Safety": "NOT_DEFINED",
                        "attackComplexity": "LOW",
                        "attackRequirements": "NONE",
                        "attackVector": "NETWORK",
                        "baseScore": 8.7,
                        "baseSeverity": "HIGH",
                        "privilegesRequired": "NONE",
                        "providerUrgency": "NOT_DEFINED",
                        "subAvailabilityImpact": "NONE",
                        "subConfidentialityImpact": "NONE",
                        "subIntegrityImpact": "NONE",
                        "userInteraction": "NONE",
                        "valueDensity": "NOT_DEFINED",
                        "vectorString": "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:H/SC:N/SI:N/SA:N",
                        "version": "4.0",
                        "vulnAvailabilityImpact": "HIGH",
                        "vulnConfidentialityImpact": "NONE",
                        "vulnIntegrityImpact": "NONE",
                        "vulnerabilityResponseEffort": "NOT_DEFINED"
                    },
                    "format": "CVSS",
                    "scenarios": [
                        {
                            "lang": "en",
                            "value": "GENERAL"
                        }
                    ]
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-400",
                            "description": "CWE-400 Uncontrolled Resource Consumption",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "orgId": "ca2a266c-be2f-4d4b-92d0-47b76b1a9c4e",
                "shortName": "Perforce",
                "dateUpdated": "2024-11-11T14:08:11.753Z"
            },
            "references": [
                {
                    "url": "https://portal.perforce.com/s/detail/a91PA000001SZOrYAO"
                }
            ],
            "source": {
                "discovery": "UNKNOWN"
            },
            "title": "Unauthenticated Denial of Service via Refuse Function in Helix Core",
            "x_generator": {
                "engine": "Vulnogram 0.2.0"
            }
        }
    }
}