{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1",
    "cveMetadata": {
        "cveId": "CVE-2025-3136",
        "assignerOrgId": "1af790b2-7ee1-4545-860a-a788eba489b5",
        "state": "PUBLISHED",
        "assignerShortName": "VulDB",
        "dateReserved": "2025-04-02T20:47:37.099Z",
        "datePublished": "2025-04-03T03:31:05.598Z",
        "dateUpdated": "2025-04-03T03:31:05.598Z"
    },
    "containers": {
        "cna": {
            "providerMetadata": {
                "orgId": "1af790b2-7ee1-4545-860a-a788eba489b5",
                "shortName": "VulDB",
                "dateUpdated": "2025-04-03T03:31:05.598Z"
            },
            "title": "PyTorch CUDACachingAllocator.cpp torch.cuda.memory.caching_allocator_delete memory corruption",
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "type": "CWE",
                            "cweId": "CWE-119",
                            "lang": "en",
                            "description": "Memory Corruption"
                        }
                    ]
                }
            ],
            "affected": [
                {
                    "vendor": "n/a",
                    "product": "PyTorch",
                    "versions": [
                        {
                            "version": "2.6.0",
                            "status": "affected"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "A vulnerability, which was classified as problematic, has been found in PyTorch 2.6.0. This issue affects the function torch.cuda.memory.caching_allocator_delete of the file c10/cuda/CUDACachingAllocator.cpp. The manipulation leads to memory corruption. An attack has to be approached locally. The exploit has been disclosed to the public and may be used."
                },
                {
                    "lang": "de",
                    "value": "Eine Schwachstelle wurde in PyTorch 2.6.0 entdeckt. Sie wurde als problematisch eingestuft. Es geht hierbei um die Funktion torch.cuda.memory.caching_allocator_delete der Datei c10/cuda/CUDACachingAllocator.cpp. Mit der Manipulation mit unbekannten Daten kann eine memory corruption-Schwachstelle ausgenutzt werden. Umgesetzt werden muss der Angriff lokal. Der Exploit steht zur öffentlichen Verfügung."
                }
            ],
            "metrics": [
                {
                    "cvssV4_0": {
                        "version": "4.0",
                        "baseScore": 4.8,
                        "vectorString": "CVSS:4.0/AV:L/AC:L/AT:N/PR:L/UI:N/VC:N/VI:N/VA:L/SC:N/SI:N/SA:N",
                        "baseSeverity": "MEDIUM"
                    }
                },
                {
                    "cvssV3_1": {
                        "version": "3.1",
                        "baseScore": 3.3,
                        "vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L",
                        "baseSeverity": "LOW"
                    }
                },
                {
                    "cvssV3_0": {
                        "version": "3.0",
                        "baseScore": 3.3,
                        "vectorString": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L",
                        "baseSeverity": "LOW"
                    }
                },
                {
                    "cvssV2_0": {
                        "version": "2.0",
                        "baseScore": 1.7,
                        "vectorString": "AV:L/AC:L/Au:S/C:N/I:N/A:P"
                    }
                }
            ],
            "timeline": [
                {
                    "time": "2025-04-02T00:00:00.000Z",
                    "lang": "en",
                    "value": "Advisory disclosed"
                },
                {
                    "time": "2025-04-02T02:00:00.000Z",
                    "lang": "en",
                    "value": "VulDB entry created"
                },
                {
                    "time": "2025-04-02T22:52:42.000Z",
                    "lang": "en",
                    "value": "VulDB entry last update"
                }
            ],
            "credits": [
                {
                    "lang": "en",
                    "value": "Default436352 (VulDB User)",
                    "type": "reporter"
                }
            ],
            "references": [
                {
                    "url": "https://vuldb.com/?id.303041",
                    "name": "VDB-303041 | PyTorch CUDACachingAllocator.cpp torch.cuda.memory.caching_allocator_delete memory corruption",
                    "tags": [
                        "vdb-entry",
                        "technical-description"
                    ]
                },
                {
                    "url": "https://vuldb.com/?ctiid.303041",
                    "name": "VDB-303041 | CTI Indicators (IOB, IOC, IOA)",
                    "tags": [
                        "signature",
                        "permissions-required"
                    ]
                },
                {
                    "url": "https://vuldb.com/?submit.525252",
                    "name": "Submit #525252 | pytorch pytorch (in torch.cuda.memory.caching_allocator_delete) torch 2.6.0 invalid memory access",
                    "tags": [
                        "third-party-advisory"
                    ]
                },
                {
                    "url": "https://github.com/pytorch/pytorch/issues/149821",
                    "tags": [
                        "issue-tracking"
                    ]
                },
                {
                    "url": "https://github.com/pytorch/pytorch/issues/149821#issuecomment-2765311086",
                    "tags": [
                        "issue-tracking"
                    ]
                },
                {
                    "url": "https://github.com/pytorch/pytorch/issues/149821#issue-2940838975",
                    "tags": [
                        "exploit",
                        "issue-tracking"
                    ]
                }
            ]
        }
    }
}