{
    "dataType": "CVE_RECORD",
    "cveMetadata": {
        "state": "PUBLISHED",
        "cveId": "CVE-2024-45201",
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "dateUpdated": "2024-08-22T19:53:12.285340",
        "dateReserved": "2024-08-22T00:00:00",
        "datePublished": "2024-08-22T00:00:00"
    },
    "containers": {
        "cna": {
            "providerMetadata": {
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre",
                "dateUpdated": "2024-08-22T19:53:12.285340"
            },
            "descriptions": [
                {
                    "lang": "en",
                    "value": "An issue was discovered in llama_index before 0.10.38. download/integration.py includes an exec call for import {cls_name}."
                }
            ],
            "affected": [
                {
                    "vendor": "n/a",
                    "product": "n/a",
                    "versions": [
                        {
                            "version": "n/a",
                            "status": "affected"
                        }
                    ]
                }
            ],
            "references": [
                {
                    "url": "https://github.com/run-llama/llama_index/pull/13523"
                },
                {
                    "url": "https://github.com/run-llama/llama_index/compare/v0.10.37...v0.10.38"
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "type": "text",
                            "lang": "en",
                            "description": "n/a"
                        }
                    ]
                }
            ]
        }
    },
    "dataVersion": "5.1"
}