{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1",
    "cveMetadata": {
        "cveId": "CVE-2024-8019",
        "assignerOrgId": "c09c270a-b464-47c1-9133-acb35b22c19a",
        "state": "PUBLISHED",
        "assignerShortName": "@huntr_ai",
        "dateReserved": "2024-08-20T17:11:51.086Z",
        "datePublished": "2025-03-20T10:08:48.918Z",
        "dateUpdated": "2025-03-20T10:08:48.918Z"
    },
    "containers": {
        "cna": {
            "title": "Arbitrary File Write/Overwrite in lightning-ai/pytorch-lightning",
            "providerMetadata": {
                "orgId": "c09c270a-b464-47c1-9133-acb35b22c19a",
                "shortName": "@huntr_ai",
                "dateUpdated": "2025-03-20T10:08:48.918Z"
            },
            "descriptions": [
                {
                    "lang": "en",
                    "value": "In lightning-ai/pytorch-lightning version 2.3.2, a vulnerability exists in the `LightningApp` when running on a Windows host. The vulnerability occurs at the `/api/v1/upload_file/` endpoint, allowing an attacker to write or overwrite arbitrary files by providing a crafted filename. This can lead to potential remote code execution (RCE) by overwriting critical files or placing malicious files in sensitive locations."
                }
            ],
            "affected": [
                {
                    "vendor": "lightning-ai",
                    "product": "lightning-ai/pytorch-lightning",
                    "versions": [
                        {
                            "version": "unspecified",
                            "lessThan": "2.3.3",
                            "status": "affected",
                            "versionType": "custom"
                        }
                    ]
                }
            ],
            "references": [
                {
                    "url": "https://huntr.com/bounties/2754298b-5af5-48ef-8b38-999093ddf2bd"
                },
                {
                    "url": "https://github.com/lightning-ai/pytorch-lightning/commit/330af381de88cff17515418a341cbc1f9f127f9a"
                }
            ],
            "metrics": [
                {
                    "cvssV3_0": {
                        "version": "3.0",
                        "attackComplexity": "LOW",
                        "attackVector": "NETWORK",
                        "availabilityImpact": "HIGH",
                        "confidentialityImpact": "NONE",
                        "integrityImpact": "HIGH",
                        "privilegesRequired": "NONE",
                        "scope": "UNCHANGED",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:H",
                        "baseScore": 9.1,
                        "baseSeverity": "CRITICAL"
                    }
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "type": "CWE",
                            "lang": "en",
                            "description": "CWE-434 Unrestricted Upload of File with Dangerous Type",
                            "cweId": "CWE-434"
                        }
                    ]
                }
            ],
            "source": {
                "advisory": "2754298b-5af5-48ef-8b38-999093ddf2bd",
                "discovery": "EXTERNAL"
            }
        }
    }
}