{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1",
    "cveMetadata": {
        "cveId": "CVE-2022-49037",
        "assignerOrgId": "db201096-a0cc-46c7-9a55-61d9e221bf01",
        "state": "PUBLISHED",
        "assignerShortName": "synology",
        "dateReserved": "2024-09-24T08:40:22.263Z",
        "datePublished": "2024-09-26T03:32:31.301Z",
        "dateUpdated": "2024-09-26T03:32:31.301Z"
    },
    "containers": {
        "cna": {
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "lang": "en",
                            "description": "CWE-532: Insertion of Sensitive Information into Log File",
                            "cweId": "CWE-532",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "affected": [
                {
                    "vendor": "Synology",
                    "product": "Synology Drive Client",
                    "versions": [
                        {
                            "version": "*",
                            "status": "affected",
                            "lessThan": "3.5.0-16084",
                            "versionType": "semver"
                        }
                    ],
                    "defaultStatus": "affected"
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "Insertion of sensitive information into log file vulnerability in proxy settings component in Synology Drive Client before 3.3.0-15082 allows remote authenticated users to obtain sensitive information via unspecified vectors."
                }
            ],
            "metrics": [
                {
                    "format": "CVSS",
                    "scenarios": [
                        {
                            "lang": "en",
                            "value": "GENERAL"
                        }
                    ],
                    "cvssV3_1": {
                        "version": "3.1",
                        "baseScore": 6.5,
                        "baseSeverity": "MEDIUM",
                        "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
                        "attackVector": "NETWORK",
                        "attackComplexity": "LOW",
                        "privilegesRequired": "LOW",
                        "userInteraction": "NONE",
                        "scope": "UNCHANGED",
                        "confidentialityImpact": "HIGH",
                        "integrityImpact": "NONE",
                        "availabilityImpact": "NONE"
                    }
                }
            ],
            "references": [
                {
                    "url": "https://www.synology.com/en-global/security/advisory/Synology_SA_24_10",
                    "name": "Synology-SA-24:10 Synology Drive Client",
                    "tags": [
                        "vendor-advisory"
                    ]
                }
            ],
            "credits": [
                {
                    "lang": "en",
                    "value": "Zhao Runzi (赵润梓)",
                    "type": "finder"
                }
            ],
            "providerMetadata": {
                "orgId": "db201096-a0cc-46c7-9a55-61d9e221bf01",
                "shortName": "synology",
                "dateUpdated": "2024-09-26T03:32:31.301Z"
            }
        }
    }
}