{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1",
    "cveMetadata": {
        "cveId": "CVE-2022-49040",
        "assignerOrgId": "db201096-a0cc-46c7-9a55-61d9e221bf01",
        "state": "PUBLISHED",
        "assignerShortName": "synology",
        "dateReserved": "2024-09-24T08:40:22.263Z",
        "datePublished": "2024-09-26T03:34:10.329Z",
        "dateUpdated": "2024-09-26T03:34:10.329Z"
    },
    "containers": {
        "cna": {
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "lang": "en",
                            "description": "CWE-120: Buffer Copy without Checking Size of Input ('Classic Buffer Overflow')",
                            "cweId": "CWE-120",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "affected": [
                {
                    "vendor": "Synology",
                    "product": "Synology Drive Client",
                    "versions": [
                        {
                            "version": "*",
                            "status": "affected",
                            "lessThan": "3.5.0-16084",
                            "versionType": "semver"
                        }
                    ],
                    "defaultStatus": "affected"
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "Buffer copy without checking size of input ('Classic Buffer Overflow') vulnerability in connection management functionality in Synology Drive Client before 3.4.0-15721 allows local users with administrator privileges to crash the client via unspecified vectors."
                }
            ],
            "metrics": [
                {
                    "format": "CVSS",
                    "scenarios": [
                        {
                            "lang": "en",
                            "value": "GENERAL"
                        }
                    ],
                    "cvssV3_1": {
                        "version": "3.1",
                        "baseScore": 4.4,
                        "baseSeverity": "MEDIUM",
                        "vectorString": "CVSS:3.1/AV:L/AC:L/PR:H/UI:N/S:U/C:N/I:N/A:H",
                        "attackVector": "LOCAL",
                        "attackComplexity": "LOW",
                        "privilegesRequired": "HIGH",
                        "userInteraction": "NONE",
                        "scope": "UNCHANGED",
                        "confidentialityImpact": "NONE",
                        "integrityImpact": "NONE",
                        "availabilityImpact": "HIGH"
                    }
                }
            ],
            "references": [
                {
                    "url": "https://www.synology.com/en-global/security/advisory/Synology_SA_24_10",
                    "name": "Synology-SA-24:10 Synology Drive Client",
                    "tags": [
                        "vendor-advisory"
                    ]
                }
            ],
            "credits": [
                {
                    "lang": "en",
                    "value": "Zhao Runzi (赵润梓)",
                    "type": "finder"
                }
            ],
            "providerMetadata": {
                "orgId": "db201096-a0cc-46c7-9a55-61d9e221bf01",
                "shortName": "synology",
                "dateUpdated": "2024-09-26T03:34:10.329Z"
            }
        }
    }
}