{
    "dataType": "CVE_RECORD",
    "cveMetadata": {
        "state": "PUBLISHED",
        "cveId": "CVE-2025-59682",
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "dateUpdated": "2025-10-01T18:51:53.204Z",
        "dateReserved": "2025-09-18T00:00:00.000Z",
        "datePublished": "2025-10-01T00:00:00.000Z"
    },
    "containers": {
        "cna": {
            "affected": [
                {
                    "defaultStatus": "unknown",
                    "product": "Django",
                    "vendor": "djangoproject",
                    "versions": [
                        {
                            "lessThan": "4.2.25",
                            "status": "affected",
                            "version": "4.2",
                            "versionType": "custom"
                        },
                        {
                            "lessThan": "5.1.13",
                            "status": "affected",
                            "version": "5.1",
                            "versionType": "custom"
                        },
                        {
                            "lessThan": "5.2.7",
                            "status": "affected",
                            "version": "5.2",
                            "versionType": "custom"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "An issue was discovered in Django 4.2 before 4.2.25, 5.1 before 5.1.13, and 5.2 before 5.2.7. The django.utils.archive.extract() function, used by the \"startapp --template\" and \"startproject --template\" commands, allows partial directory traversal via an archive with file paths sharing a common prefix with the target directory."
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-23",
                            "description": "CWE-23 Relative Path Traversal",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre",
                "dateUpdated": "2025-10-01T18:51:53.204Z"
            },
            "references": [
                {
                    "url": "https://docs.djangoproject.com/en/dev/releases/security/"
                },
                {
                    "url": "https://groups.google.com/g/django-announce"
                },
                {
                    "url": "https://www.djangoproject.com/weblog/2025/oct/01/security-releases/"
                }
            ],
            "x_generator": {
                "engine": "enrichogram 0.0.1"
            },
            "metrics": [
                {
                    "cvssV3_1": {
                        "version": "3.1",
                        "baseScore": 3.1,
                        "baseSeverity": "LOW",
                        "vectorString": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:N/I:L/A:N"
                    }
                }
            ],
            "cpeApplicability": [
                {
                    "nodes": [
                        {
                            "operator": "OR",
                            "negate": false,
                            "cpeMatch": [
                                {
                                    "vulnerable": true,
                                    "criteria": "cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*",
                                    "versionStartIncluding": "4.2",
                                    "versionEndExcluding": "4.2.25"
                                },
                                {
                                    "vulnerable": true,
                                    "criteria": "cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*",
                                    "versionStartIncluding": "5.1",
                                    "versionEndExcluding": "5.1.13"
                                },
                                {
                                    "vulnerable": true,
                                    "criteria": "cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*",
                                    "versionStartIncluding": "5.2",
                                    "versionEndExcluding": "5.2.7"
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    },
    "dataVersion": "5.1"
}